# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=16)),
                ('author_belong', models.CharField(max_length=8)),
                ('author_birth', models.CharField(max_length=8)),
                ('author_death', models.CharField(max_length=8)),
                ('author_desc', models.TextField()),
                ('author_head_thumb', models.CharField(max_length=128)),
                ('entity_type', models.CharField(default=b'author', max_length=16)),
            ],
            options={
                'db_table': 'author_table',
            },
        ),
        migrations.CreateModel(
            name='Author_Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(default=b'author_poem', max_length=16)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReadingAssistant.Author')),
            ],
            options={
                'db_table': 'author_poem_table',
            },
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('emotion_id', models.AutoField(primary_key=True, serialize=False)),
                ('emotion_desc', models.TextField()),
                ('entity_type', models.CharField(default=b'emotion', max_length=16)),
            ],
            options={
                'db_table': 'emotion_table',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=32)),
                ('entity_type', models.CharField(default=b'image', max_length=16)),
            ],
            options={
                'db_table': 'image_table',
            },
        ),
        migrations.CreateModel(
            name='Image_Emotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(default=b'image_emotion', max_length=16)),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReadingAssistant.Emotion')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReadingAssistant.Image')),
            ],
            options={
                'db_table': 'image_emotion_table',
            },
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('poem_id', models.AutoField(primary_key=True, serialize=False)),
                ('poem_name', models.CharField(max_length=64)),
                ('poem_content', models.TextField()),
                ('poem_pinyin', models.TextField(null=True)),
                ('poem_analysis', models.TextField()),
                ('poem_kind', models.CharField(max_length=32, null=True)),
                ('poem_year', models.CharField(max_length=8, null=True)),
                ('entity_type', models.CharField(default=b'poem', max_length=16)),
            ],
            options={
                'db_table': 'poem_table',
            },
        ),
        migrations.CreateModel(
            name='Poem_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(default=b'poem_image', max_length=16)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReadingAssistant.Image')),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReadingAssistant.Poem')),
            ],
            options={
                'db_table': 'poem_image_table',
            },
        ),
        migrations.AddField(
            model_name='author_poem',
            name='poem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReadingAssistant.Poem'),
        ),
    ]
